---
title: "open payments"
author: "Marie Moriarty"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Data cleaning
```{r cleaning, warning=FALSE}
library(readr)
library(dplyr)
library(tidyverse)
payments <- read_csv("Open_Payment_south_dakota_2013-18.csv")

# Delete unnecessary columns, convert all characters to uppercase
payments <- payments %>%
  filter(covered_recipient_type == "Covered Recipient Physician" &
           total_amount_of_payment_usdollars > 0) %>%
  select(-c(covered_recipient_type, 
            teaching_hospital_ccn, 
            teaching_hospital_id,
            teaching_hospital_name,
            physician_name_suffix,
            recipient_state,
            recipient_country,
            recipient_province,
            recipient_postal_code,
            applicable_manufacturer_or_applicable_gpo_making_payment_id,
            charity_indicator,
            delay_in_publication_indicator)) %>%
  mutate_all(.funs=toupper)

# Change date and numeric types
payments$physician_profile_id <- as.integer(payments$physician_profile_id)
payments$date_of_payment <- as.Date(payments$date_of_payment)
payments$payment_publication_date <- as.Date(payments$payment_publication_date)
payments$total_amount_of_payment_usdollars <- as.numeric(payments$total_amount_of_payment_usdollars)

# Create single name variable
payments$physician_name <- 
  paste(payments$physician_first_name,
      payments$physician_last_name,
      sep = " ")

# Delete other name variables
payments <- payments %>%
  select(-c(physician_first_name,
            physician_middle_name,
            physician_last_name))

#Convert to factors
payments[,-c(2:4,18,19,31,60,61)] <- lapply(payments[,-c(2:4,18,19,31,60,61)],factor)

# Fix typos - will work on more later
levels(payments$recipient_city)[levels(payments$recipient_city)
                                =="BOBRIDGE"] <- "MOBRIDGE"

levels(payments$recipient_city)[levels(payments$recipient_city)
                                == "SIOUXFALLS"|
                                  levels(payments$recipient_city)
                                == "SIOUS FALLS"|
                                  levels(payments$recipient_city)
                                == "SIOUX FALLAS"|
                                  levels(payments$recipient_city)
                                == "AVE SIOUX FALLS"|
                                  levels(payments$recipient_city)
                                == "SIOUX FALL"] <- "SIOUX FALLS"
levels(payments$recipient_city)[levels(payments$recipient_city)
                                == "RA[ID CITY"|
                                  levels(payments$recipient_city)
                                == "RAPIID CITY"] <- "RAPID CITY"
levels(payments$recipient_city)[levels(payments$recipient_city)
                                == "N SIOUX CITY"|
                                  levels(payments$recipient_city)
                                == "NORTH SIOU"|
                                  levels(payments$recipient_city)
                                == "SIOUX CITY"] <- "NORTH SIOUX CITY"
levels(payments$recipient_city)[levels(payments$recipient_city)
                                == "400 22ND AVE"] <- "BROOKINGS"
```
### Exploratory plots
```{r plots, warning=FALSE}
library(ggplot2)
library(plotly)

new.payments <- read.csv("new_open_payment_sd_MMoriarty.csv",header=TRUE)

payments$physician_name <- as.factor(payments$physician_name)

physician_amount <- aggregate(payments$total_amount_of_payment_usdollars, 
                        by = list(payments$physician_name,
                                  payments$recipient_city),
                        FUN = sum)

physician_amount <- physician_amount %>%
  rename(Physician = Group.1,
         City = Group.2,
         Total = x)

payment_totals <-
  ggplot(physician_amount, aes(Total)) +
  geom_histogram(data=subset(physician_amount, City=="SIOUX FALLS"),fill="blue") +
  labs(title="Total payments ($) received per physician") + 
  #theme(axis.text.x = element_blank()) + 
  xlim(0.01,1000)

ggplot(physician_amount, aes(Physician, Total)) +
  geom_point(data=subset(physician_amount, City=="RAPID CITY"), alpha= 0.5) +
  labs("Total payment amounts by physician, Rapid City") + 
  theme(axis.text.x = element_blank()) + 
  ylim(0.01,50000)

ggplotly(payment_totals)
```


```{r app code}
library(ggplot2)
library(plotly)

new.payments <- read_csv("new_open_payment_sd_MMoriarty.csv")

phys_amount <- aggregate(new.payments$total_amount_of_payment_usdollars, 
                        by = list(new.payments$physician_name,
                                  new.payments$recipient_city),
                        FUN = sum)

phys_amount <- phys_amount %>%
  rename(Physician = Group.1,
         City = Group.2,
         Total = x)

payment_totals <-
  ggplot(phys_amount, aes(Total, na.rm=TRUE)) +
            geom_histogram(data=subset(phys_amount, 
                                       City=="SIOUX FALLS" & 
                                       !is.na(Total) & Total > 50000),
                           fill="blue",
                           bins=100) +
            labs(title="Total payments ($) received per physician") + 
            xlab("Total payments received ($)") 

ggplotly(payment_totals)
```

```{r}
write.csv(phys_amount, "physician_totals.csv")
```
